In [1]:
import pandas as pd

In [2]:
weather = pd.read_csv('blood data/2012-2021 기상.csv' , encoding = 'CP949')
weather_co =weather.copy()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
weather_co2= weather_co[weather_co['예보시각'].str.contains('오전')]

In [4]:
weather_co2.drop(columns='발표시각', inplace= True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [5]:
weather_co2.sort_values(by=['지역','예보시각'])

          지역           예보시각    예보  신뢰도  강수확률(%)
24      강원영동  2012-12-20 오전  구름조금   보통      NaN
108     강원영동  2012-12-20 오전    맑음   보통      NaN
25      강원영동  2012-12-21 오전  구름많음   낮음      NaN
110     강원영동  2012-12-21 오전  구름많음   보통      NaN
228     강원영동  2012-12-21 오전  구름많음   보통      NaN
...      ...            ...   ...  ...      ...
786985  충청북도  2021-04-09 오전    맑음  NaN     10.0
787114  충청북도  2021-04-09 오전    맑음  NaN      0.0
787244  충청북도  2021-04-09 오전    맑음  NaN     10.0
787115  충청북도  2021-04-10 오전  구름많음  NaN     30.0
787245  충청북도  2021-04-10 오전  구름많음  NaN     30.0

[475440 rows x 5 columns]

In [6]:
weather_co3= weather.copy()

In [7]:
weather_co3[weather_co3['발표시각'].str.contains('06시')]

                  발표시각        지역           예보시각           예보  신뢰도  강수확률(%)
0       2012-12-18 06시  서울.인천.경기  2012-12-20 오전         구름많음   보통      NaN
1       2012-12-18 06시  서울.인천.경기  2012-12-21 오전  구름많고 비 또는 눈   보통      NaN
2       2012-12-18 06시  서울.인천.경기  2012-12-22 오전         구름많음   보통      NaN
3       2012-12-18 06시  서울.인천.경기  2012-12-23 오전         구름조금   보통      NaN
4       2012-12-18 06시  서울.인천.경기  2012-12-24 오전         구름조금   보통      NaN
...                ...       ...            ...          ...  ...      ...
787215  2021-03-31 06시      경상남도  2021-04-07 오전         구름많음  NaN     30.0
787216  2021-03-31 06시      경상남도  2021-04-07 오후         구름많음  NaN     20.0
787217  2021-03-31 06시      경상남도  2021-04-08 오전           맑음  NaN     10.0
787218  2021-03-31 06시      경상남도  2021-04-09 오전           맑음  NaN     10.0
787219  2021-03-31 06시      경상남도  2021-04-10 오전           흐림  NaN     40.0

[393640 rows x 6 columns]

In [26]:
weather_1 = weather_co3[weather_co3['발표시각'].str.contains('18시')]

In [27]:
weather_2 = weather_1[weather_1['예보시각'].str.contains('오전')]

In [28]:
weather_3 = weather_2.drop(columns='발표시각')

In [29]:
weather_4 = weather_3.drop(columns=['신뢰도','강수확률(%)'])

In [30]:
weather_4

              지역           예보시각    예보
60      서울.인천.경기  2012-12-20 오전  구름조금
62      서울.인천.경기  2012-12-21 오전  구름많음
64      서울.인천.경기  2012-12-22 오전  구름많음
66      서울.인천.경기  2012-12-23 오전  구름조금
68      서울.인천.경기  2012-12-24 오전    맑음
...          ...            ...   ...
787343      경상남도  2021-04-06 오전  구름많음
787345      경상남도  2021-04-07 오전  구름많음
787347      경상남도  2021-04-08 오전    맑음
787348      경상남도  2021-04-09 오전    맑음
787349      경상남도  2021-04-10 오전    흐림

[237730 rows x 3 columns]

In [31]:
weather_4['예보'].value_counts()

구름많음        117236
구름조금         53990
맑음           32006
흐리고 비        16153
구름많고 비        7407
흐림            6256
구름많고 눈        1322
구름많고 비/눈      1161
흐리고 비/눈        904
구름많고 눈/비       627
흐리고 눈          492
흐리고 눈/비        176
Name: 예보, dtype: int64

In [33]:
weather_5 = weather_4['예보'].replace('구름많고 눈/비','구름많고 비/눈')
weather_5 = weather_5.replace('흐리고 눈/비','흐리고 비/눈')
weather_5.value_counts()

구름많음        117236
구름조금         53990
맑음           32006
흐리고 비        16153
구름많고 비        7407
흐림            6256
구름많고 비/눈      1788
구름많고 눈        1322
흐리고 비/눈       1080
흐리고 눈          492
Name: 예보, dtype: int64

In [36]:
weather_4['예보']= weather_5

In [38]:
weather_4['예보'].value_counts()

구름많음        117236
구름조금         53990
맑음           32006
흐리고 비        16153
구름많고 비        7407
흐림            6256
구름많고 비/눈      1788
구름많고 눈        1322
흐리고 비/눈       1080
흐리고 눈          492
Name: 예보, dtype: int64

In [52]:
weather_4.sort_values(by= ['지역','예보시각'])

          지역           예보시각        예보
108     강원영동  2012-12-20 오전        맑음
110     강원영동  2012-12-21 오전      구름많음
348     강원영동  2012-12-21 오전      구름많음
112     강원영동  2012-12-22 오전  구름많고 비/눈
350     강원영동  2012-12-22 오전      구름많음
...      ...            ...       ...
786984  충청북도  2021-04-08 오전        맑음
787243  충청북도  2021-04-08 오전        맑음
786985  충청북도  2021-04-09 오전        맑음
787244  충청북도  2021-04-09 오전        맑음
787245  충청북도  2021-04-10 오전      구름많음

[237730 rows x 3 columns]

In [70]:
weather_4[['지역','예보시각']].sort_values(['지역','예보시각'])

          지역           예보시각
108     강원영동  2012-12-20 오전
110     강원영동  2012-12-21 오전
348     강원영동  2012-12-21 오전
112     강원영동  2012-12-22 오전
350     강원영동  2012-12-22 오전
...      ...            ...
786984  충청북도  2021-04-08 오전
787243  충청북도  2021-04-08 오전
786985  충청북도  2021-04-09 오전
787244  충청북도  2021-04-09 오전
787245  충청북도  2021-04-10 오전

[237730 rows x 2 columns]

In [73]:
weather_4.query('지역  == "강원영동"').sort_values('예보시각').head(10)

       지역           예보시각        예보
108  강원영동  2012-12-20 오전        맑음
110  강원영동  2012-12-21 오전      구름많음
348  강원영동  2012-12-21 오전      구름많음
112  강원영동  2012-12-22 오전  구름많고 비/눈
350  강원영동  2012-12-22 오전      구름많음
588  강원영동  2012-12-22 오전      구름조금
114  강원영동  2012-12-23 오전      구름조금
828  강원영동  2012-12-23 오전        맑음
352  강원영동  2012-12-23 오전      구름조금
590  강원영동  2012-12-23 오전      구름조금